apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccess
metadata:
  name: devuser-b-bucketaccess
  namespace: devuser-b
spec:
  bucketAccessClassName: cosi-nutanix-nkp
  bucketClaimName: devuser-b
  credentialsSecretName: devuser-b-bucket-credentials
  protocol: s3