apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccess
metadata:
  name: forrester-bucketaccess
  namespace: default
spec:
  bucketAccessClassName: cosi-nutanix-nkp
  bucketClaimName: forrester-bucket
  credentialsSecretName: forrester-demo-bucket-credentials
  protocol: s3