## Example for a dev user with a separate namespace and bucket claim

apiVersion: v1
kind: Namespace
metadata:
  name: devuser-a
---
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClaim
metadata:
  name: devuser-a
  namespace: devuser-a
spec:
  bucketClassName: cosi-nutanix-nkp
  protocols:
   - s3